import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  BookOpenText,
  BookUser,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarIcon,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleX,
  ClipboardCheck,
  ClipboardCopy,
  Copy,
  Database,
  Download,
  ExternalLink,
  FileDown,
  FileJson,
  FilePlus2,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  GitCompareArrows,
  GraduationCap,
  History,
  ImagePlus,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  LayoutList,
  Lightbulb,
  LineChart,
  Link2,
  ListChecks,
  ListEnd,
  ListTodo,
  Loader2,
  Lock,
  LogOut,
  Map,
  MapPin,
  MapPinOff,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquareQuote,
  Minus,
  Moon,
  MoreHorizontal,
  NotebookPen,
  PackagePlus,
  PencilLine,
  Plug,
  Plus,
  Radar,
  Receipt,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Satellite,
  Save,
  ScrollText,
  Search,
  SearchCheck,
  Send,
  Settings,
  ShieldCheck,
  ShieldX,
  Sparkles,
  Split,
  Stamp,
  Star,
  Stethoscope,
  Sun,
  Swords,
  Tags,
  Trash2,
  TrendingUp,
  TriangleAlert,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type IconName = keyof typeof Icons;

export const Icons = {
  add: Plus,
  alert: CircleAlert,
  alertTriangle: AlertTriangle,
  analytics: LineChart,
  approve: CheckCircle2,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  audit: ScrollText,
  bell: Bell,
  blog: NotebookPen,
  bookUser: BookUser,
  building: Building2,
  calendar: CalendarIcon,
  calendarClock: CalendarClock,
  calendarDays: CalendarDays,
  calendarRange: CalendarRange,
  check: Check,
  checkCircle: CircleCheck,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  clipboard: ClipboardCopy,
  clipboardCheck: ClipboardCheck,
  close: X,
  compare: GitCompareArrows,
  copy: Copy,
  dashboard: LayoutDashboard,
  data: Database,
  download: Download,
  edit: PencilLine,
  empty: Inbox,
  error: CircleX,
  export: FileDown,
  external: ExternalLink,
  fileJson: FileJson,
  filePlus: FilePlus2,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  flask: FlaskConical,
  graduationCap: GraduationCap,
  history: History,
  image: ImagePlus,
  info: Info,
  layers: Layers,
  layoutList: LayoutList,
  lightbulb: Lightbulb,
  link: Link2,
  listChecks: ListChecks,
  listEnd: ListEnd,
  listTodo: ListTodo,
  loading: Loader2,
  lock: Lock,
  logOut: LogOut,
  map: Map,
  mapPin: MapPin,
  mapPinOff: MapPinOff,
  messageSquare: MessageSquare,
  minus: Minus,
  moon: Moon,
  more: MoreHorizontal,
  package: PackagePlus,
  pencil: PencilLine,
  plug: Plug,
  radar: Radar,
  receipt: Receipt,
  refresh: RefreshCw,
  refreshCcw: RefreshCcw,
  reply: MessageSquareQuote,
  review: MessageCircleQuestion,
  rocket: Rocket,
  satellite: Satellite,
  save: Save,
  search: Search,
  searchCheck: SearchCheck,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  shieldX: ShieldX,
  sort: ArrowDown,
  sparkles: Sparkles,
  split: Split,
  stamp: Stamp,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  swords: Swords,
  tags: Tags,
  trash: Trash2,
  trendingUp: TrendingUp,
  user: UserRound,
  userPlus: UserPlus,
  usersGroup: Users,
  wallet: Wallet,
  warning: TriangleAlert,
  wrench: Wrench,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;
